### ISSUE TITLE
Fix floating image bug

### ISSUE THREAD

**Issue by kyaso** [bitsandvolts/bitsandvolts.github.io#22]
## Description
When reloading a page/post with _floating_ images, it can happen that some images appear at positions they are not supposed to be in.

## Example
(from post dd_00001)

Original:
![Screenshot from 2021-05-05 00-28-51](https://user-images.githubusercontent.com/18646029/117077801-0c895500-ad39-11eb-96bf-124707c5d52d.png)

After reloading page:
![Screenshot from 2021-05-05 00-29-08](https://user-images.githubusercontent.com/18646029/117077818-127f3600-ad39-11eb-904b-833ede2ed3d0.png)

An attempt to mitigate this issue is currently in progress: #21

**Comment by leboem** [comment]
Is this issue finally solved? If yes, you can close it
